app/autoparts/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView
)

API_PREFIX = 'api'
DOCS_PREFIX = 'docs'
DEFAULT_API_VERSION = 'v1'

schema_view = get_schema_view(
    openapi.Info(
        title=settings.DRF_YASG['PROJECT_NAME'],
        default_version=DEFAULT_API_VERSION,
        description=settings.DRF_YASG['DESCRIPTION'],
    ),
    public=True
)

# REST API V1 urls
api_v1_urlpatterns = [
    path(f"{API_PREFIX}/{DEFAULT_API_VERSION}/ebay/",
         include(('ebay.api.v1.urls', 'ebay'), namespace=DEFAULT_API_VERSION), name='ebay')
]

# simplejwt urls
jwt_urlpatterns = [
    path(f"{API_PREFIX}/{DEFAULT_API_VERSION}/token/", TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path(f"{API_PREFIX}/{DEFAULT_API_VERSION}/token/refresh/", TokenRefreshView.as_view(), name='token_refresh'),
    path(f"{API_PREFIX}/{DEFAULT_API_VERSION}/token/verify/", TokenVerifyView.as_view(), name='token_verify'),
]

# drf-yasg
drf_yasg_urlpatterns = [
    url(r'^api/v1/swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    url(r'^api/v1/swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    url(r'^api/v1/redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

# Media & static files urls
static_media_urlpatterns = static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
                           + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Apps urls
apps_urlpatterns = [
    path('ebay/', include('ebay.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns = api_v1_urlpatterns \
              + jwt_urlpatterns \
              + static_media_urlpatterns \
              + apps_urlpatterns

if settings.DEBUG:
    urlpatterns += drf_yasg_urlpatterns

app/ebay/api/v1/urls.py
from django.urls import path

from ebay.api.v1.views import EbaySearch, EbayProductDetailsView

urlpatterns = [
    path('search/', EbaySearch.as_view()),
    path('product/<id>', EbayProductDetailsView.as_view())
]

app/ebay/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('search/', views.search, name='search'),
]

app/ebay/models.py
import datetime

from common.models import CoreModel
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class Credential(CoreModel):
    """
    Credential model
    """

    app_id = models.CharField(
        max_length=40,
        unique=True,
        blank=False,
        null=False,
        # default=None, null=False trick used here to work around with known
        # Django's `get_default` empty string that creates instance with empty-string
        # CharField avoiding any validation. So you are able get get an exception making Model.objects.create()
        default=None,
        verbose_name=_("AppID/ClientID"),
        help_text=_("AppID/ClientID that will be used to perform eBay API requests. Max. length 40 characters.")
    )
    cert_id = models.CharField(
        max_length=40,
        unique=True,
        # TODO: change on blank False, null=False, when db will ready.
        blank=True,
        null=True,
        # default=None, null=False trick used here to work around with known
        # Django's `get_default` empty string that creates instance with empty-string
        # CharField avoiding any validation. So you are able get get an exception making Model.objects.create()
        default=None,
        verbose_name=_("CertID"),
        help_text=_("CertID that will be used to perform eBay API requests. Max. length 40 characters.")
    )
    is_primary = models.BooleanField(
        default=False,
        verbose_name=_("Primary"),
        help_text=_("Only one credential can be primary at same time.")
    )

    query_count = models.IntegerField(
        default=0,
        verbose_name=_("QueryCount"),
        help_text=_("Count query to the ebay with these credentials per dey")
    )

    api_limit_mtime = models.DateTimeField(
        null=True,
        blank=True,
        verbose_name=_("ApiLimitMTime"),
        help_text=_("Time when api limit was expired")
    )

    def save(self, *args, **kwargs):
        # Set `is_primary=False` for Credential with `is_primary=True` if instance is set to `is_primary=True`
        super().save(*args, **kwargs)

        if self.query_count > 4950 and self.api_limit_mtime == None:
            print('it was saved again')
            self.api_limit_mtime = datetime.datetime.now()
            self.is_primary = False
            new_primary = Credential.objects.filter(query_count__lte=4950, api_limit_mtime__isnull=True).first()
            if new_primary:
                new_primary.is_primary = True
                new_primary.save()
            else:
                date_from = datetime.datetime.now() - datetime.timedelta(days=1)

                new_primary = Credential.objects.filter(api_limit_mtime__lte=date_from).first()
                if new_primary:
                    new_primary.query_count = 0
                    new_primary.api_limit_mtime = None
                    new_primary.is_primary = True
                    new_primary.save()

        if self.is_primary is True:
            Credential.objects.exclude(pk=self.pk).update(is_primary=False)

    def __str__(self):
        return f"{self.pk}: {self.app_id}"


class Vendor(CoreModel):
    """
    Vendor model
    """
    name = models.CharField(
        max_length=255,
        verbose_name=_("Vendor"),
        help_text=_("Name of the product vendor")
    )
    url = models.URLField(
        null=True,
        verbose_name=_("Link"),
        help_text=_("Product Vendor Link")
    )

    class Meta:
        app_label = 'ebay'
        verbose_name = "Vendor"
        verbose_name_plural = "Vendors"

    def __str__(self):
        return self.name


class Product(CoreModel):
    """
    Product model
    """
    vendor = models.ForeignKey(
        'ebay.Vendor',
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        verbose_name="Vendor",
        help_text=_("Product vendor")
    )
    ebay_id = models.BigIntegerField(
        null=True,
        blank=True,
        verbose_name=_("eBay Item ID"),
        help_text=_("eBay Item ID from API")
    )
    brand = models.CharField(
        null=True,
        max_length=80,
        verbose_name=_("Brand"),
        help_text=_("Max. length 80 characters.")
    )
    part_number = models.CharField(
        null=True,
        max_length=80,
        verbose_name=_("Part number"),
        help_text=_("Max. length 80 characters.")
    )
    title = models.CharField(
        max_length=255,
        verbose_name=_("Title"),
        help_text=_("Max. length 80 characters.")
    )
    description = models.TextField(
        null=True,
        blank=True,
        verbose_name=_("Description"),
        help_text=_("May contain HTML tags.")
    )
    location = models.CharField(
        max_length=45,
        verbose_name=_("Location"),
        help_text=_("Max. length 45 characters.")
    )
    condition = models.CharField(
        null=True,
        max_length=32,
        verbose_name=_("Condition"),
        help_text=_("Max. length 32 characters.")
    )
    price = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        verbose_name=_("Price"),
        help_text=_("All prices are in USD currency.")
    )
    url = models.URLField(
        max_length=300,
        verbose_name=_("URL"),
        help_text=_("Product URL on eBay.")
    )
    thumbnail_url = models.URLField(
        null=True,
        verbose_name=_("Thumbnail URL"),
        help_text=_("Product thumbnail URL on eBay.")
    )
    # hash field is being used to check if item has been updated from last fetching
    hash = models.CharField(
        max_length=32,
        editable=False,
        verbose_name=_("Hash"),
        help_text=_("Hash that allows to check if product was changed from last update.")
    )
    top_rated_seller = models.BooleanField(
        default=False,
        verbose_name=_("Is top rated seller"),
        help_text=_("Determines that seller is top rated within eBay.")
    )
    buy_it_now = models.BooleanField(
        default=False,
        verbose_name=_("Is but it now"),
        help_text=_("Determines that product is available for buy it now option.")
    )
    country = models.CharField(
        max_length=2,
        null=True,
        help_text=_("ISO 3166 country code. Max. length 2 characters.")
    )

    seller = models.ForeignKey(
        'ebay.Seller',
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        verbose_name="Seller",
        help_text=_("Seller of the product")
    )

    def __str__(self):
        return f"{self.pk}: {self.ebay_id} - {self.title}"


class Search(CoreModel):
    owner = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name=_("Owner"),
        help_text=_("Search request initiator"),
    )
    keyword = models.CharField(
        max_length=255,
        verbose_name=_("Search keyword"),
        help_text=_("Max. length 255 characters."),
    )
    # hash field is being used to check if items have been updated from last fetching
    hash = models.CharField(
        max_length=32,
        editable=False,
        verbose_name=_("Hash"),
        help_text=_("Hash that allows to check if search results were changed from last update.")
    )
    session = models.UUIDField(
        default=None,
        null=True,
        editable=False,
        verbose_name=_("Session UUID"),
        help_text=_("Used to determine search query session.")
    )
    brand_types = models.CharField(
        null=True,
        blank=True,
        max_length=1000,
        verbose_name=_("Brand Types"),
        help_text=_("Max. length 1000 characters")
    )
    compatibility = models.CharField(
        null=True,
        blank=True,
        max_length=1000,
        verbose_name=_("Compatibility"),
        help_text=_("Max. length 1000 characters")
    )
    max_delivery_cost = models.BooleanField(
        null=True,
        blank=True,
        verbose_name=_("Max Delivery Cost"),
        help_text=_("False if free shipping")
    )
    conditions = models.CharField(
        null=True,
        blank=True,
        max_length=1000,
        verbose_name=_("Conditions"),
        help_text=_("Max. length 1000 characters")
    )

    def __str__(self):
        return f"{self.keyword}: {self.hash}"


class SearchIndex(CoreModel):
    """
        Search index model
    """
    search = models.ForeignKey(
        'ebay.Search',
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        help_text=_("Search id")
    )
    vendors = models.ManyToManyField(Vendor, blank=True)
    top_product = models.ManyToManyField(Product, blank=True)
    keywords = models.CharField(
        max_length=255,
        verbose_name=_("Search index keyword"),
        help_text=_("Max. length 255 characters."),
    )
    description = models.TextField(
        null=True,
        blank=True,
        verbose_name=_("Description"),
        help_text=_("May contain HTML tags.")
    )
    image = models.URLField(
        null=True,
        verbose_name=_("Image url"),
        help_text=_("Image URL")
    )

    class Meta:
        app_label = 'ebay'
        verbose_name = "Search index"
        verbose_name_plural = "Search indexes"

    def __str__(self):
        return self.keyword


class SearchProduct(CoreModel):
    search = models.ForeignKey(
        Search,
        related_name="search_product",
        on_delete=models.CASCADE,
        verbose_name=_("Search"),
        help_text="Many to one relations with Search table"
    )
    product = models.ForeignKey(
        Product,
        related_name="search_product",
        on_delete=models.CASCADE,
        verbose_name=_("Product"),
        help_text="Many to one relations with Product table"
    )

    class Meta:
        app_label = "ebay"
        verbose_name = "Search Product"

app/ebay/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.shortcuts import render
from .services import EbayService, EbayServiceError


@login_required(login_url='/admin/login/')
def search(request):
    # Deny from all except is_staff user
    if not request.user.is_staff:
        raise PermissionDenied

    # Error messages queue
    error_messages: list = []

    search_results = []
    query = request.GET.get('query', '')
    per_page = request.GET.get('per_page', 50)
    page = request.GET.get('page', 1)

    try:
        ebay = EbayService(auto_save=True)
    except EbayServiceError as error:
        error_messages.append(error.__str__())

    if request.GET and query != '':
        try:
            search_results = ebay.search(keywords=query, per_page=per_page, page=page, owner=request.user.pk)
        except EbayServiceError as error:
            error_messages.append(error.__str__())

    return render(request, "ebay/search/index.html", {
        'error_messages': error_messages,
        'response': search_results,
        'form': {
            'query': query,
            'per_page': int(per_page),
            'page': int(page)
        }
    })

app/ebay/templates/ebay/search/index.html
{% extends "ebay/base.html" %}
{% block page_heading %}{% endblock %}
{% block title %}Search{% endblock %}
{% block content %}
    <div class="container mx-auto py-4">
        {% if error_messages %}
            {% for error_message in error_messages %}
                <p class="p-4 bg-red-100 font-light mb-4">{{ error_message }}</p>
            {% endfor %}
        {% endif %}
        <form action="" method="get">
            <div class="flex w-full">
                <input type="search" class="w-full py-2 px-4 shadow-md ring-1 outline-none font-light" id="id_search"
                       name="query" aria-describedby="inputNameHelp"
                       placeholder="Search" value="{{ form.query }}">
                <button type="submit"
                        class="w-96 py-2 px-4 bg-blue-500 text-white font-light shadow-md outline-none ring-1">
                    Submit
                </button>
            </div>
            {% if response and not error_messages %}
                <label for="per_page">Per page</label>
                <select class="ring-1 ring-black-500" name="per_page" id="per_page" onchange="this.form.submit();">
                    <option value="1" {% if form.per_page == 1 %}selected{% endif %}>1</option>
                    <option value="10" {% if form.per_page == 10 %}selected{% endif %}>10</option>
                    <option value="50" {% if form.per_page == 50 %}selected{% endif %}>50</option>
                    <option value="100" {% if form.per_page == 100 %}selected{% endif %}>100</option>
                </select>
{# TODO: it increases page laoding time, we need create links or something else instead of select #}
{#                <label for="page">Page</label>#}
{#                <select class="ring-1 ring-black-500" name="page" id="page" onchange="this.form.submit()">#}
{#                    {% load ebay_filters %}#}
{#                    {% for page in response.paginationOutput.totalPages|times %}#}
{#                        <option value="{{ page }}" {% if form.page == page %}selected{% endif %}>{{ page }}</option>#}
{#                    {% endfor %}#}
{#                </select>#}
            {% endif %}
        </form>
        {% if response and not error_messages %}
            <div class="">
                <p>Page: {{ response.paginationOutput.pageNumber }}/{{ response.paginationOutput.totalPages }}</p>
                <p>Per
                    page/Total: {{ response.paginationOutput.entriesPerPage }}/{{ response.paginationOutput.totalEntries }}</p>
            </div>
            <table class="table-fixed border-separate border border-black">
                <thead>
                <tr class="text-left border-1 border-black-500">
                    <th class="w-1/6 border border-black-500">image</th>
                    <th class="w-1/10 border border-black-500">id</th>
                    <th class="w-1/4 border border-black-500">title</th>
                    <th class="w-1/6 border border-black-500">price</th>
                    <th class="w-1/6 border border-black-500">location</th>
                    <th class="w-1/6 border border-black-500">condition</th>
                </tr>
                </thead>
                <tbody>
                {% for item in response.searchResult.item %}
                    <tr class="border border-black-500">
                        <td class="border border-black-500">
                            <img class="object-cover" width="140" height="140" src="{{ item.galleryURL }}">
                        </td>
                        <td class="border border-black-500">{{ item.itemId }}</td>
                        <td class="border border-black-500">
                            <a href="{{ item.viewItemURL }}" class="underline" target="_blank">{{ item.title }}</a>
                        </td>
                        <td class="border border-black-500">{{ item.sellingStatus.currentPrice.value }}</td>
                        <td class="border border-black-500">{{ item.location }}</td>
                        <td class="border border-black-500">{{ item.condition.conditionDisplayName }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% endif %}
    </div>
{% endblock %}